spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}

fcm:
  project-id: ${FCM_PROJECT_ID}
  private-key-id: ${FCM_PRIVATE_KEY_ID}
  private-key: ${FCM_PRIVATE_KEY}
  client-email: ${FCM_CLIENT_EMAIL}
  client-id: ${FCM_CLIENT_ID}
  auth-uri: ${FCM_AUTH_URI}
  token-uri: ${FCM_TOKEN_URI}
  auth-provider-x509-cert-url: ${FCM_AUTH_PROVIDER_CERT_URL}
  client-x509-cert-url: ${FCM_CLIENT_CERT_URL}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
  secure: ${CLOUDINARY_SECURE}

r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key-id: ${R2_ACCESS_KEY_ID}
  secret-access-key: ${R2_SECRET_ACCESS_KEY}
  bucket-name: ${R2_BUCKET_NAME}
  public-base-url: ${R2_PUBLIC_BASE_URL}

gemini:
  api-key: ${GEMINI_API_KEY}

